[package]
name = "ap-relay"
description = "A simple activitypub relay"
version = "0.3.50"
authors = ["asonix <asonix@asonix.dog>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://git.asonix.dog/asonix/ap-relay"
keywords = ["activitypub", "relay"]
edition = "2021"
build = "src/build.rs"

[[bin]]
name = "relay"
path = "src/main.rs"

[features]
console = ["console-subscriber"]
default = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
actix-rt = "2.7.0"
actix-web = { version = "4.0.1", default-features = false }
actix-webfinger = "0.4.0"
activitystreams = "0.7.0-alpha.19"
activitystreams-ext = "0.1.0-alpha.2"
ammonia = "3.1.0"
awc = { version = "3.0.0", default-features = false, features = ["rustls"] }
bcrypt = "0.13"
base64 = "0.13"
clap = { version = "4.0.0", features = ["derive"] }
config = "0.13.0"
console-subscriber = { version = "0.1", optional = true }
dashmap = "5.1.0"
dotenv = "0.15.0"
futures-util = "0.3.17"
lru = "0.8.0"
mime = "0.3.16"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-otlp = "0.11"
rand = "0.8"
rsa = "0.7"
rsa-magic-public-key = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = { version = "0.10", features = ["oid"] }
signature = "1.6.4"
sled = "0.34.7"
teloxide = { version = "0.11.1", default-features = false, features = [
  "ctrlc_handler",
  "macros",
  "rustls",
] }
thiserror = "1.0"
tracing = "0.1"
tracing-awc = "0.1.6"
tracing-error = "0.2"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-opentelemetry = "0.18"
tracing-subscriber = { version = "0.3", features = [
  "ansi",
  "env-filter",
  "fmt",
] }
tokio = { version = "1", features = ["macros", "sync"] }
uuid = { version = "1", features = ["v4", "serde"] }

[dependencies.background-jobs]
version = "0.13.0"
default-features = false
features = ["background-jobs-actix", "error-logging"]

[dependencies.http-signature-normalization-actix]
version = "0.6.0"
default-features = false
features = ["client", "server", "sha-2"]

[dependencies.tracing-actix-web]
version = "0.6.1"

[build-dependencies]
anyhow = "1.0"
dotenv = "0.15.0"
ructe = { version = "0.15.0", features = ["sass", "mime03"] }
toml = "0.5.8"

[profile.dev.package.rsa]
opt-level = 3
